### ISSUE TITLE
View description of classes  

### ISSUE THREAD

**Issue by MartinGaiser** [mobileappdevhm/team2#12]
# Motivation:
As a user, I want to be able to tap on the course and see its description.

# Technical description:

# Acceptance criteria:
- Description box pops up when the course is tapped
- Includes course description, day, time, lecturer’s contact info, ...

> [Link to original Issue in Main Repository](http://9gag.com)

**Comment by hmkrivoj** [comment]
Instead of using a popup dialog I'm gonna take the user to a new screen with an option on going back.
A new screen offers more space for displaying informations than a small popup dialog window.
