### ISSUE TITLE
Create GitHub Pages

### ISSUE THREAD

**Issue by Gleydar** [mobileappdevhm/team2#122]
Create GitHub Pages to have a website

**Comment by mariomeissner** [comment]
Would be good know exactly what we should include here.

**Comment by Gleydar** [comment]
According do Mrs. Socher it should be an 'outside view' of the project - so maybe a description of the features, some screenshots and a download button (At least I'd say)
I mean, for the technical side we have a wiki

**Comment by l0renor** [comment]
i did a few things but there ist a download button yea and we need a cow annimation as well
