### ISSUE TITLE
Bookmark courses / shopping cart

### ISSUE THREAD

**Issue by BullshitPingu** [mobileappdevhm/team2#14]
# Motivation
As a user, I want to be able to bookmark the courses I am interested in, and be able to see a list of all the courses I have bookmarked.

# Acceptance criteria
Button or gesture that bookmarks a course and offers visual feedback on completed action.
List of bookmarked courses visible and scrollable.

**Comment by mariomeissner** [comment]
Duplicate.

**Comment by hmkrivoj** [comment]
Removed from project as this one is a duplicate. See #19
