### ISSUE TITLE
Bug: Search text keeps showing in bar after switching to different screen

### ISSUE THREAD

**Issue by hmkrivoj** [mobileappdevhm/team2#167]

**Comment by mariomeissner** [comment]
Will look into this now.

**Comment by mariomeissner** [comment]
Cannot reproduce.

**Comment by hmkrivoj** [comment]
@VoitreX  How did it happen to you today?

**Comment by hmkrivoj** [comment]
Steps to reproduce:
Select department 07
Switch to different screen

App bar shows "search: FK07"

**Comment by mariomeissner** [comment]
Make sure you are on the latest version?
This does not happen to me.

**Comment by mariomeissner** [comment]
Fixed the bug I commented above and cannot reproduce the other one. Please reopen if it still happens to you on latest version of sprint3 branch.

**Comment by hmkrivoj** [comment]
latest version of branch sprint3
sent video of bug via telegram

**Comment by hmkrivoj** [comment]
Decided to not fix
