### ISSUE TITLE
Some courses crash the app

### ISSUE THREAD

**Issue by Gleydar** [mobileappdevhm/team2#182]
These courses have the deparment -1 and a description of null, crashing the app when trying to open them.

**Comment by Gleydar** [comment]
List of all courses that crash the app:
* Composite Materials
* Single track vehicle design
* Digital Control Systems
* Plant Engineering
* Organic and Printed Electronics
* Digital Color
* Marketing
* Advanced fluid mechanics
* Fluid Mechanics
* Automation I 
* Statistics
* Sustainable
* Modelling and Testing of Products
* Tool Design and Manufacture
* Design of Integrated Circuits
* Operating Systems 1
* Technical Writing in computer science I 
* Network Management
* Secure Network Management
* Intercultural Aspects in Project Management
* Compiler Construction
* Concepts of modern programming languages
* Ergonomics and Practical Training
* Technical Marketing
* Marketing and Sales, Automobile
* Sustainability in Supply Chain Management
* Strategic Marketing by Online Simulation
* Inbound / Outbound Logistics
* Managing Change
* Intercultural Management
* Agile Project Management
* Project Studies
* International Management
* Intercultural Buisness Communication
* Intercultural Competence
* International Economics
* International Finace Modelin
* Financial Modeling
* Corporate Leadership
* International Strategy and Sales Management
* International Operations
* Buisness Innovation
* Digital Buisness
* Technology Risk Management
* Digital Technology Management
* Corporate Finance
* Customer Interaction
* Design of Digital Products
* Frankenstein reloaded
* Improvisaton Theatre
* What do you really know when you get information
* From ancient utopias to cyberutpias
* Historical buildings and monuments
* Management simulation
* HR Transformation
* Special Aspects in Turism
* International Marketing

**Comment by hmkrivoj** [comment]
Looking into it

**Comment by hmkrivoj** [comment]
Fixed with #178
