### ISSUE TITLE
Migrate Backlog

### ISSUE THREAD

**Issue by l0renor** [mobileappdevhm/team2#2]

**Comment by BullshitPingu** [comment]
Thumbs up!

**Comment by BullshitPingu** [comment]
https://docs.google.com/document/d/1ToeoDpaGMN3bgvJopB67P6taWdaB5k7np2TSiufGznA/edit#heading=h.phvqaxjdeoba

**Comment by BullshitPingu** [comment]
Please check if we really have all issues from the backlog.

**Comment by BullshitPingu** [comment]
Isnt this done yet?

**Comment by l0renor** [comment]
the google doc is private i cant acsess it

**Comment by mariomeissner** [comment]
https://github.com/mobileappdevhm/CiEApp/wiki/Product-Backlog

**Comment by l0renor** [comment]
i'll take down teh dead link in the wiki as well
