### ISSUE TITLE
Export Favorites/Sign up for favorites

### ISSUE THREAD

**Issue by MartinGaiser** [mobileappdevhm/team2#21]
# Motivation:
As a user i want to have my Courses that I actually want to take in a seperate List and be able to submit them for registration.

# Techincal description:

# Acceptance criteria:
- Button or gesture that puts a course in the shopping cart and offers visual feedback on completed action.
- List of courses in the shopping cart.

> [Link to original Issue in Main Repository](http://9gag.com)

**Comment by MartinGaiser** [comment]
I've pushed a new Branch "exportFavourites" which contains a button and a alert Dialog to Export the Favourites list.
The actual export feature still needs to be implemented.

**Comment by Gleydar** [comment]
#112

**Comment by MartinGaiser** [comment]
Working on extra button to Pull Lottery results to current favourites.

**Comment by MartinGaiser** [comment]
This is done in the Settings Page already .... can be closed.
