### ISSUE TITLE
Date/Time W/ class that occurs more than one day a week

### ISSUE THREAD

**Issue by VoitreX** [mobileappdevhm/team2#66]
There is a possible problem with our data structure, Timetable, Course description, and Course Tiles.
Currently we don't support classes with more than one day a week meeting time.

**Comment by mariomeissner** [comment]
This is why I discouraged showing the course times in the CourseListEntry as well.

## Proposal:
Courses should have an Events array where each event is either a Lecture or a Lab and has a date and time. Then the timetable just neets to loop over all events and show each one as an individual entry.

**Comment by Gleydar** [comment]
Closed with #107
