### ISSUE TITLE
Timetable Exception

### ISSUE THREAD

**Issue by Gleydar** [mobileappdevhm/team2#69]
`E/flutter (23781): setState() called after dispose(): TimetableState#984f2(lifecycle state: defunct, not mounted)
E/flutter (23781): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback. The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter (23781): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter (23781): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1098:9)
E/flutter (23781): #1      State.setState (package:flutter/src/widgets/framework.dart:1124:6)
E/flutter (23781): #2      TimetableState.build.<anonymous closure> (package:courses_in_english/ui/screens/timetable_screen.dart:28:9)
E/flutter (23781): #3      _RootZone.runUnary (dart:async/zone.dart:1381:54)
E/flutter (23781): #4      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
E/flutter (23781): #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633:45)
E/flutter (23781): #6      Future._propagateToListeners (dart:async/future_impl.dart:662:32)
E/flutter (23781): #7      Future._complete (dart:async/future_impl.dart:467:7)
E/flutter (23781): #8      new Future.delayed.<anonymous closure> (dart:async/future.dart:310:16)
E/flutter (23781): #9      Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
E/flutter (23781): #10     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
E/flutter (23781): #11     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
E/flutter (23781): #12     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)´

**Comment by hmkrivoj** [comment]
Was already fixed with #61
