### ISSUE TITLE
Rework timetable page, add export

### ISSUE THREAD

**Issue by l0renor** [mobileappdevhm/team2#7]
Motivation: As a user, I want to be able to see the timetable of the courses I’m taking. 
Technical description:
Acceptance criteria:
Visible timetable containing courses enrolled in this semester
Export button for exporting the timetable to iCal, pdf, etc.
Tags/categories:basic features

**Comment by hmkrivoj** [comment]
Fixing error #61 and doing some graphical refinement...

**Comment by hmkrivoj** [comment]
Fixed error
Aber das Grafische mache ich nicht mehr... Ist nicht mein Kind das Ding - mich juckts nicht wenn's hässlich ist 🤡

**Comment by hmkrivoj** [comment]
Graphical improvements postponed for sprint2

**Comment by Gleydar** [comment]
done with #107
