### ISSUE TITLE
Local Storage of our data model

### ISSUE THREAD

**Issue by Gleydar** [mobileappdevhm/team2#83]
We need a cool data model which:
- handles relations between objects (Right now the objects contain ids to relate to other objects)
- caches the objects so that we dont need additional server requests

**Comment by Gleydar** [comment]
Implement SQLite for Sprint 2

**Comment by VoitreX** [comment]
Working on it now, will also implement putters so someone can sync this with the server

**Comment by Gleydar** [comment]
Will be fixed with #117

**Comment by hmkrivoj** [comment]
Postponed for Sprint3 due to changes from #115
