### ISSUE TITLE
Overflow on Course Details Widget

### ISSUE THREAD

**Issue by jonasreitemeyer** [mobileappdevhm/team2#95]
Currently appearing at Marketing Mock Course

**Comment by hmkrivoj** [comment]
Can you submit a screenshot?

**Comment by hmkrivoj** [comment]
bump

**Comment by jonasreitemeyer** [comment]
![screenshot_20180604-143817](https://user-images.githubusercontent.com/15349525/40918065-836b8444-6805-11e8-8c62-b18bed4b4b02.jpg)

**Comment by Gleydar** [comment]
AAAAAANd its gone!
