### ISSUE TITLE
FavoritesScreen glitch

### ISSUE THREAD

**Issue by hmkrivoj** [mobileappdevhm/team2#99]
## Description: 
Removing courses from your favorites on the FavoriteScreen leads to unexpected behaviour. The removed course stays within the list. Instead a different course disappears from the screen. However debugging and logging say that the unfavorized course is indeed removed from the list of favorites. The build-method also doesn't create a widget for this course, which is the expected behaviour. Nevertheless this course is displayed on the screen. Maybe it's a bug in the flutter framework?

## How to reproduce: 
Add some courses to your favorites.
Now go to the favorites screen and remove one of these courses.

**Comment by mariomeissner** [comment]
Looking into this.

**Comment by mariomeissner** [comment]
Seems like 'unhearting' a course, no matter which one, will remove the last course in the list always. It probably has something to do with indexing.

**Comment by mariomeissner** [comment]
The issue could potentially be solved by turning the whole thing stateless. 
I'll attempt to do this and submit a PR.

**Comment by hmkrivoj** [comment]
Fixed with #115 and #114
